### ISSUE TITLE
gstreamer helper knows only x86 arches

### ISSUE THREAD

**Issue by sharkcz** [PackageKit/PackageKit#326]
The gstreamer helper knows only x86 arches (32 and 64 bit), thus it fails to help to install a codec on my ppc64le machine. The problem is in the [pk_gst_get_arch_suffix()](https://github.com/hughsie/PackageKit/blob/master/contrib/gstreamer-plugin/pk-gstreamer-install.c#L209) function that uses a hardcoded list of arches compared to uname() output. I think a better way is needed to determine if the `()(64bit)` suffix should be appended.

On a Fedora 29 for ppc64le running parole player under XFCE desktop I get
````
** Message: 09:59:59.051: PackageKit: xid = 46139404
** Message: 09:59:59.051: PackageKit: desktop_id = (null)

** (gst-install-plugins-helper:2799): WARNING **: 09:59:59.051: PackageKit: did not recognise machine type: 'ppc64le'
** Message: 09:59:59.051: PackageKit: Codec nice name: H.264 (High Profile) decoder
** Message: 09:59:59.051: PackageKit: ignoring field named level
** Message: 09:59:59.051: PackageKit: ignoring field named profile
** Message: 09:59:59.051: PackageKit: ignoring field named interlace-mode
** Message: 09:59:59.051: PackageKit: ignoring field named chroma-format
** Message: 09:59:59.051: PackageKit: ignoring field named bit-depth-luma
** Message: 09:59:59.051: PackageKit: ignoring field named bit-depth-chroma
** Message: 09:59:59.051: PackageKit: structure: gstreamer1(decoder-video/x-h264)
** Message: 09:59:59.059: PackageKit: Did not install codec: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.PackageKit was not provided by any .service files
````
I still need to figure out why it complains about the ServiceUnknown even when PackageKit is installed.

**Comment by kalev** [comment]
The unknown service error is because you have nothing installed that provides the _session_ dbus service. The session dbus service is implemented by gnome-software, gnome-packagekit, the KDE package center etc.

**Comment by sharkcz** [comment]
Hmm, simply installing gnome-packagekit didn't help.

**Comment by kalev** [comment]
Ah, oops, I forgot that hughsie removed the session service from gnome-packagekit a few years ago after we implemented it in gnome-software.

**Comment by sharkcz** [comment]
OK, to summarize the desktop must provide a session org.freedesktop.PackageKit service (as opposed to a system service provided by PackageKit) for the helper to work.

The 64-bit arch problem is still there, wonder if a check "if sizeof(long) == 8; then warn && assume 64-bit suffix" solution would be acceptable? Or does glib provide an API for such check?

**Comment by kalev** [comment]
Yep, correct. The desktop has to provide session org.freedesktop.PackageKit service.

Sure, checking the size of long (or void pointer) sounds like a good plan to me.

**Comment by sidt4** [comment]
It appears this is fixed by https://github.com/PackageKit/PackageKit/pull/327 ?

**Comment by sharkcz** [comment]
that's correct, closing
